name = "workers-graphql-server"
type = "webpack"
zone_id = ""
account_id = "24f5c57e1b3f502cbc33525eb6e29acb"
route = ""
workers_dev = true
webpack_config = "webpack.config.js"

# Enable a kv-namespace to use the KV caching feature
#
# kv-namespaces = [
#   { binding = "WORKERS_GRAPHQL_CACHE", id = "" }
# ]
